name: CI
on:
  - push
env:
  PROJECT_IMAGE: hexletprojects/js_l1_brain_games4_project
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@release
        with:
          project_image: ${{ env.PROJECT_IMAGE }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: build package
        run: |
          make install
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
